context: centos7
required: true

branches:
    - master
    - auto
    - try

host:
    distro: centos/7/atomic

tests:
  - env BWRAP_SUID=true ./ci/redhat-ci.sh centos:7

timeout: 30m

---

inherit: true

context: f25-asan-ubsan
required: true

tests:
  - env CFLAGS='-g -Og -fsanitize=undefined -fsanitize=address' ./ci/redhat-ci.sh fedora:25
